// http://docs.aws.amazon.com/AWSMechTurk/latest/AWSMechanicalTurkRequester/MakingRequests_RequestAuthenticationArticle.html

// 1 The sender constructs a request to AWS.
// 2 The sender calculates a Keyed-Hashing for Message Authentication code (HMAC), the request signature using the his or her Secret Access Key and the values of the Service, Operation, and Timestamp parameters as input.
// 3 The sender of the request sends the request data, the signature, and Access Key ID (the key-identifier of the Secret Access Key used) to AWS.
// 4 AWS uses the Access Key ID to look up the Secret Access Key.
// 5 AWS generates a signature from the request data and the Secret Access Key using the same algorithm used to calculate the signature in the request.
// 6 If the signature generated by AWS matches the one sent in the request, the request is considered to be authentic. If the comparison fails, the request is discarded, and AWS returns an error response.

package route53

import (
	"bytes"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"net/http"
	"time"
)

const postURL = `https://route53.amazonaws.com/2012-12-12/hostedzone`

type AccessIdentifiers struct {
	AccessKey string
	SecretKey string
	time      time.Time
}

func remoteTime(url string) (time string, err error) {
	headers, err := remoteHeaders(url)
	if err != nil {
		return time, err
	}
	time = headers.Get("Date")
	return
}

func remoteHeaders(url string) (http.Header, error) {
	resp, err := http.Head(url)
	if err != nil {
		return nil, err
	}
	return resp.Header, nil
}

func (a *AccessIdentifiers) CreateSignature() (sha string) {
	if a.time.IsZero() {
		a.time = time.Now()
	}
	time := a.time.UTC().Format(time.ANSIC)
	hash := hmac.New(sha256.New, []byte(a.SecretKey))
	hash.Write([]byte(time))
	sha = base64.StdEncoding.EncodeToString(hash.Sum(nil))
	return
}

func (a *AccessIdentifiers) CreateHeaders() http.Header {
	if a.time.IsZero() {
		a.time = time.Now()
	}
	signature := a.CreateSignature()
	h := http.Header{}
	h.Add("Date", a.time.UTC().Format(time.ANSIC))
	h.Add("Content-Type", "text/xml; charset=UTF-8")
	h.Add("X-Amzn-Authorization",
		"AWS3-HTTPS AWSAccessKeyId="+a.AccessKey+",Algorithm=HmacSHA256,Signature="+signature)
	return h
}

func RemotePost(url string, postData string, a AccessIdentifiers) (*http.Response, error) {
	req, err := http.NewRequest("POST", url, bytes.NewReader([]byte(postData)))
	if err != nil {
		return nil, err
	}
	req.Header = a.CreateHeaders()
	client := &http.Client{}
	res, err := client.Do(req)
	if err != nil {
		return nil, err
	}

	return res, err
}
